// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/fercho/school-tracking/services/notification/internal/core/domain"
	mock "github.com/stretchr/testify/mock"

	services "github.com/fercho/school-tracking/services/notification/internal/core/ports/services"

	uuid "github.com/google/uuid"
)

// MockNotificationService is an autogenerated mock type for the NotificationService type
type MockNotificationService struct {
	mock.Mock
}

// GetNotification provides a mock function with given fields: ctx, id
func (_m *MockNotificationService) GetNotification(ctx context.Context, id uuid.UUID) (*domain.Notification, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetNotification")
	}

	var r0 *domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Notification, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Notification); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListNotifications provides a mock function with given fields: ctx, req
func (_m *MockNotificationService) ListNotifications(ctx context.Context, req services.ListNotificationsRequest) ([]*domain.Notification, int, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListNotifications")
	}

	var r0 []*domain.Notification
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, services.ListNotificationsRequest) ([]*domain.Notification, int, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.ListNotificationsRequest) []*domain.Notification); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.ListNotificationsRequest) int); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, services.ListNotificationsRequest) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RetryFailed provides a mock function with given fields: ctx
func (_m *MockNotificationService) RetryFailed(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RetryFailed")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendPush provides a mock function with given fields: ctx, req
func (_m *MockNotificationService) SendPush(ctx context.Context, req services.SendPushRequest) (*domain.Notification, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SendPush")
	}

	var r0 *domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.SendPushRequest) (*domain.Notification, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.SendPushRequest) *domain.Notification); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.SendPushRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendSMS provides a mock function with given fields: ctx, req
func (_m *MockNotificationService) SendSMS(ctx context.Context, req services.SendSMSRequest) (*domain.Notification, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SendSMS")
	}

	var r0 *domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.SendSMSRequest) (*domain.Notification, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.SendSMSRequest) *domain.Notification); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.SendSMSRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockNotificationService creates a new instance of MockNotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationService {
	mock := &MockNotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
