// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPushNotifier is an autogenerated mock type for the PushNotifier type
type MockPushNotifier struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, userID, title, body, data
func (_m *MockPushNotifier) Send(ctx context.Context, userID string, title string, body string, data string) error {
	ret := _m.Called(ctx, userID, title, body, data)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, userID, title, body, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockPushNotifier creates a new instance of MockPushNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPushNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPushNotifier {
	mock := &MockPushNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
