// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSMSSender is an autogenerated mock type for the SMSSender type
type MockSMSSender struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, toPhone, body
func (_m *MockSMSSender) Send(ctx context.Context, toPhone string, body string) error {
	ret := _m.Called(ctx, toPhone, body)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, toPhone, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockSMSSender creates a new instance of MockSMSSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSMSSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSMSSender {
	mock := &MockSMSSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
